---

- include: "/usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/initialize_groups.yml"
- include: "/usr/share/ansible/openshift-ansible/playbooks/common/openshift-cluster/evaluate_groups.yml"

- name: Create hosted resources
  hosts: masters[0]
  tasks:
    - include_role:
        name: openshift_hosted
        tasks_from: ./router/router
      vars:
        openshift_hosted_manage_router: true
        openshift_hosted_manage_registry: false

