---
# If interim dns is installed, DNS nameserver should be updated
- name: Check if iterim dns ip exist in /etc/resolv.conf
  command: "grep {{hostvars['localhost']['ansible_controller_ip']}} /etc/resolv.conf"
  register: interim_dns_ip_exist
  ignore_errors: yes
  when: interim_dns.install

- name: Add interim dns ip to all nodes
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    line: "PEERDNS=no"
  with_items:
    - "{{ interim_dns_ip_exist }}"
  when: interim_dns.install and item.rc == 1

- name: Add interim dns ip to all nodes
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    line: "DNS1={{hostvars['localhost']['ansible_controller_ip']}}"
  with_items:
    - "{{ interim_dns_ip_exist }}"
  when: interim_dns.install and item.rc == 1

