---
- shell: subscription-manager repos --list-enabled  |grep 'Repo ID'|awk  '{print $3}'
  register: enabled_repo_list

- name: Disable unneeded repositories
  command: subscription-manager repos --disable='*'
  register: subs_disable
  async: 1800
  poll: 0
  when: need_repo_list|difference(enabled_repo_list.stdout_lines)|length != 0 

- name: Wait for disable unneeded repositories
  async_status: jid="{{ subs_disable.ansible_job_id }}"
  register: jobs
  until: jobs.finished
  retries: 180
  delay: 5
  when: need_repo_list|difference(enabled_repo_list.stdout_lines)|length != 0 

- name: Enable OpenShift repositories
  command: subscription-manager repos --enable="{{item}}" 
  with_items:
    - "{{ need_repo_list }}"
  register: subs_enable
  async: 1800
  poll: 0
  when: need_repo_list|difference(enabled_repo_list.stdout_lines)|length != 0 

- debug: var=subs_enable
- name: Wait for Enable OpenShift repositories
  async_status: jid="{{ item.ansible_job_id }}"
  register: jobs
  until: jobs.finished
  retries: 180
  delay: 7
  with_items:
    - "{{ subs_enable.results }}"
  when: need_repo_list|difference(enabled_repo_list.stdout_lines)|length != 0 


