---
- import_tasks: ./manage-repositories.yaml

- name: Install the required rpms
  shell: yum install -y wget git yum-utils net-tools bind-utils iptables-services bridge-utils bash-completion kexec-tools sos psacct atomic-openshift-utils atomic-openshift-excluder atomic-openshift-docker-excluder
  register: rpm_install
  async: 1800
  poll: 0

- name: Wait for Enable OpenShift repositories
  async_status: jid="{{ rpm_install.ansible_job_id }}"
  register: jobs
  until: jobs.finished
  retries: 180
  delay: 10

