---
- hosts: localhost
  tasks:
  - name: Add ansible controller to memory if you are already on your own ansible controller
    add_host:
       name: "{{ansible_fqdn}}"
       groups: ansible-controller
    when: "not 'ansible-controller' in groups"


- hosts: ansible-controller
  tasks:
    - name: Register RHSM for Ansible Controller
      include_role:
         name: subscription_attach
      vars:
         pool_name: "{{subs.broker_sub_pool  | default(false)}}"
         pool_id: "{{subs.broker_sub_pool_id  | default(false)}}"

    - name: Prerequisite for ansible controller
      include_role:
        name: openshift-prerequisites
      vars:
        node_type: ansible-controller 

    - name: Download get-pip.py for pip packaging util
      get_url:
         url: https://bootstrap.pypa.io/get-pip.py
         dest: /tmp/get-pip.py
         mode: 777
    
    - name: Install pip
      command: "python /tmp/get-pip.py"
  
    - name: Install ovirt-engine-sdk-python
      command: "{{ item }}"
      with_items:
        -  "pip install ovirt-engine-sdk-python "
  
    - name: Check out official ansible github repository
      git: 
        repo: "{{ item.url }}"
        dest: "/root/git/{{ item.folder_name }}"   
      with_items:
        - { url: 'https://github.com/ansible/ansible.git', folder_name: 'ansible' }
        - { url: 'https://github.com/Jooho/ansible-playbook-deploy-ocp-on-rhev.git', folder_name: 'ansible-playbook-deploy-ocp-on-rhev' }
      ignore_errors: yes

## 2.4 is releasd so it does not need anymore
#    - name: Gather file info for modules
#      command: "ls -al /root/git/ansible/lib/ansible/modules/cloud/ovirt/ovirt*"
#      register: ovirt_module_files
#
#   - name: Copy some latest modules to ansible-cheat-sheet repo
#     command: "cp {{ item }} /root/git/ansible-cheat-sheet/ansible-playbooks/ansible-playbook-deploy-ocp-on-rhev/modules"
#     with_items:
#        - "{{ovirt_module_files.stdout_lines}}"
#        - "/root/git/ansible/lib/ansible/modules/packaging/os/redhat_subscription.py"
  
